export const metadata = {
  title: "Lobby King",
  description: "Generated by create next app",
};

import { MatchesDataProvider } from "@/hooks/useMatchesData";
import { OpenFilesProvider } from "@/hooks/useOpenFiles";

import { Explorer } from "@/components/Explorer";
import { InputAddMatch } from "@/components/InputAddMatch";
import { OpenFilesTabs } from "@/components/OpenFilesTabs";

import Image from "next/image";
import headerDota from "../assets/header-dota.png";
import bgDota from "../assets/bg-dota.jpg";

import { Inter } from "next/font/google";
import "../styles/global.css";

const inter = Inter({ subsets: ["latin"] });

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" className={inter.className}>
      <body className="bg-gradient-to-b from-slate-900 via-slate-600 to-slate-900">
        <div className="z-10 h-screen p-20 flex items-center justify-center">
          <div className=" w-full max-w-[1180px] aspect-video border border-[#444] rounded-2xl relative">
            <Image
              src={headerDota}
              alt=""
              quality={100}
              className="rounded-2xl w-full absolute z-10"
              priority
            />
            <MatchesDataProvider>
              <OpenFilesProvider>
                <div className="grid grid-cols-[200px,1fr] h-full">
                  <div
                    className="bg-gradient-to-b from-[#161214] via-[#754436] to-[#161214]
       rounded-bl-2xl rounded-tl-2xl pt-14 flex flex-col justify-between"
                  >
                    <Explorer />

                    <InputAddMatch />
                  </div>

                  <div className="h-full relative flex flex-col">
                    <Image
                      src={bgDota}
                      alt=""
                      fill={true}
                      sizes="100%"
                      quality={100}
                      priority
                      className="object-cover rounded-br-2xl rounded-tr-2xl -z-10 w-full"
                    />
                    <OpenFilesTabs />

                    <div className="h-full object-fill">{children}</div>
                  </div>
                </div>
              </OpenFilesProvider>
            </MatchesDataProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
