export const metadata = {
  title: "Lobby King",
  description: "Generated by create next app",
};

import Image from "next/image";
import headerDota from "../assets/header-dota.png";

import { Inter } from "next/font/google";
import "../styles/global.css";

const inter = Inter({ subsets: ["latin"] });

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" className={inter.className}>
      <body className="bg-gradient-to-b from-slate-900 via-slate-600 to-slate-900">
        <div className="z-10 h-screen p-20 flex items-center justify-center">
          <div className=" w-full max-w-[1180px] aspect-video border border-[#444] rounded-2xl relative">
            <Image
              src={headerDota}
              alt=""
              quality={100}
              className="rounded-2xl w-full absolute z-10"
              priority
            />
            <div className="h-full object-fill">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
